/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import atoresPrincipais.Clinica;
import atoresPrincipais.Medico;
import atoresSecundários.Paciente;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class MenuMedPac extends javax.swing.JFrame {

    /**
     * Creates new form MenuMedPac
     */
    Clinica clinica;
    Paciente paciente;
    Medico medico;
    EntityManagerFactory emf;

    public MenuMedPac(EntityManagerFactory emf, Clinica clinica, Medico medico, Paciente paciente) {
        this.clinica = clinica;
        this.paciente = paciente;
        this.medico = medico;
        this.emf = emf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameGeraAtest = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaJust = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButtonSalvarAtest = new javax.swing.JButton();
        jFormattedTextFieldDataIni = new javax.swing.JTextField();
        jFormattedTextFieldDatafim = new javax.swing.JTextField();
        jFrameGeraAcomp = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaJustifi = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButtonSalvarAcomp = new javax.swing.JButton();
        jFormattedTextFieldData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonHome = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonExibePac = new javax.swing.JButton();
        jButtonDadoAdicional = new javax.swing.JButton();
        jButtonProntuario = new javax.swing.JButton();
        jButtonGeraAt = new javax.swing.JButton();
        jButtonGeraRec1 = new javax.swing.JButton();
        jButtonGeraAt1 = new javax.swing.JButton();

        jFrameGeraAtest.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Data de inicio:");

        jLabel3.setText("Data de fim:");

        jTextAreaJust.setColumns(20);
        jTextAreaJust.setRows(5);
        jScrollPane1.setViewportView(jTextAreaJust);

        jLabel4.setText("Justificativa:");

        jButtonSalvarAtest.setText("Salvar");
        jButtonSalvarAtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAtestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameGeraAtestLayout = new javax.swing.GroupLayout(jFrameGeraAtest.getContentPane());
        jFrameGeraAtest.getContentPane().setLayout(jFrameGeraAtestLayout);
        jFrameGeraAtestLayout.setHorizontalGroup(
            jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameGeraAtestLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jFrameGeraAtestLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarAtest))
                    .addGroup(jFrameGeraAtestLayout.createSequentialGroup()
                        .addGroup(jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldDataIni)
                            .addComponent(jFormattedTextFieldDatafim, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jFrameGeraAtestLayout.setVerticalGroup(
            jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameGeraAtestLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldDatafim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jFrameGeraAtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameGeraAtestLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameGeraAtestLayout.createSequentialGroup()
                        .addComponent(jButtonSalvarAtest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        jFrameGeraAcomp.setSize(new java.awt.Dimension(362, 269));

        jLabel5.setText("Data:");

        jLabel6.setText("Nome do Acompanhante:");

        jTextAreaJustifi.setColumns(20);
        jTextAreaJustifi.setRows(5);
        jScrollPane2.setViewportView(jTextAreaJustifi);

        jLabel7.setText("Justificativa:");

        jButtonSalvarAcomp.setText("Salvar");
        jButtonSalvarAcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAcompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameGeraAcompLayout = new javax.swing.GroupLayout(jFrameGeraAcomp.getContentPane());
        jFrameGeraAcomp.getContentPane().setLayout(jFrameGeraAcompLayout);
        jFrameGeraAcompLayout.setHorizontalGroup(
            jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jButtonSalvarAcomp)
                        .addContainerGap())
                    .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                        .addGroup(jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNome)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addGap(28, 28, 28))))
        );
        jFrameGeraAcompLayout.setVerticalGroup(
            jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGroup(jFrameGeraAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrameGeraAcompLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonSalvarAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(530, 355));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Menu do Paciente");

        jToolBar1.setRollover(true);

        jButtonHome.setText("H");
        jButtonHome.setFocusable(false);
        jButtonHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonHome);

        jButtonAnterior.setText("A");
        jButtonAnterior.setFocusable(false);
        jButtonAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAnterior);

        jButtonExibePac.setText("Exibir Paciente");
        jButtonExibePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibePacActionPerformed(evt);
            }
        });

        jButtonDadoAdicional.setText("Gerenciar Dados Adicionais");
        jButtonDadoAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadoAdicionalActionPerformed(evt);
            }
        });

        jButtonProntuario.setText("Gerenciar Prontuarios");
        jButtonProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProntuarioActionPerformed(evt);
            }
        });

        jButtonGeraAt.setText("Gerar Declaração de Acompanhamento");
        jButtonGeraAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeraAtActionPerformed(evt);
            }
        });

        jButtonGeraRec1.setText("Gerar Receita (N)");
        jButtonGeraRec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeraRec1ActionPerformed(evt);
            }
        });

        jButtonGeraAt1.setText("Gerar Atestado");
        jButtonGeraAt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeraAt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addComponent(jButtonExibePac)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProntuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDadoAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGeraAt)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButtonGeraRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(80, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGeraAt1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExibePac)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonGeraRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDadoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(jButtonGeraAt1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonGeraAt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        dispose();
        MenuEntrar main = new MenuEntrar(emf, clinica);
        main.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        dispose();
        MenuMed menMed = new MenuMed(emf, clinica, medico);
        menMed.setVisible(true);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonExibePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibePacActionPerformed
        JOptionPane.showMessageDialog(null, paciente.imprimirPaciente(), "Paciente", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonExibePacActionPerformed

    private void jButtonDadoAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadoAdicionalActionPerformed
        dispose();
        MenuMedPacDaAd mDados = new MenuMedPacDaAd(emf, clinica, medico, paciente);
        mDados.setVisible(true);

    }//GEN-LAST:event_jButtonDadoAdicionalActionPerformed

    private void jButtonSalvarAtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAtestActionPerformed
        String dataIni = jFormattedTextFieldDataIni.getText();
        String dataFim = jFormattedTextFieldDatafim.getText();
        String Justif = jTextAreaJust.getText();
        JOptionPane.showMessageDialog(null, medico.geraAtestado(dataIni, dataFim, Justif, paciente.getCpf(), emf), "Atestado", HEIGHT);

        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDatafim.setText("");
        jTextAreaJust.setText("");
        jFrameGeraAtest.dispose();
    }//GEN-LAST:event_jButtonSalvarAtestActionPerformed

    private void jButtonGeraRec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeraRec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGeraRec1ActionPerformed

    private void jButtonGeraAt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeraAt1ActionPerformed
        jFrameGeraAtest.setVisible(true);
    }//GEN-LAST:event_jButtonGeraAt1ActionPerformed

    private void jButtonGeraAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeraAtActionPerformed
        jFrameGeraAcomp.setVisible(true);
    }//GEN-LAST:event_jButtonGeraAtActionPerformed

    private void jButtonSalvarAcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAcompActionPerformed
        String justif = jTextAreaJustifi.getText();
        String nomeAcomp = jTextFieldNome.getText();
        String data = jFormattedTextFieldData.getText();

        JOptionPane.showMessageDialog(null, medico.geraDeclaracaoAcompanhamento(justif, nomeAcomp, data, paciente.getCpf(), emf), "Declaração de acompanhamento", HEIGHT);

        jTextAreaJustifi.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldData.setText("");

        jFrameGeraAcomp.dispose();
    }//GEN-LAST:event_jButtonSalvarAcompActionPerformed

    private void jButtonProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProntuarioActionPerformed
        dispose();
        MenuMedPacProntu MenuPront = new MenuMedPacProntu(emf, clinica, medico, paciente);
        MenuPront.setVisible(true);
    }//GEN-LAST:event_jButtonProntuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonDadoAdicional;
    private javax.swing.JButton jButtonExibePac;
    private javax.swing.JButton jButtonGeraAt;
    private javax.swing.JButton jButtonGeraAt1;
    private javax.swing.JButton jButtonGeraRec1;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonProntuario;
    private javax.swing.JButton jButtonSalvarAcomp;
    private javax.swing.JButton jButtonSalvarAtest;
    private javax.swing.JTextField jFormattedTextFieldData;
    private javax.swing.JTextField jFormattedTextFieldDataIni;
    private javax.swing.JTextField jFormattedTextFieldDatafim;
    private javax.swing.JFrame jFrameGeraAcomp;
    private javax.swing.JFrame jFrameGeraAtest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaJust;
    private javax.swing.JTextArea jTextAreaJustifi;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
