/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import atoresPrincipais.Clinica;
import atoresPrincipais.Medico;
import atoresSecundários.Paciente;
import static classesAuxiliares.Buscas.buscaPacienteConsulta;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Emanuel
 */
public class MenuMed extends javax.swing.JFrame {

    /**
     * Creates new form MenuMed
     */
    
    Clinica clinica;
    Medico medico;
    public MenuMed(Clinica clinica, Medico medico) {
        this.clinica = clinica;
        this.medico = medico;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEscolhaPac = new javax.swing.JFrame();
        jComboBoxPacienteEsco = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonSalvarEscolha = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAcessarPacientes = new javax.swing.JButton();
        jButtonPacientesNoMes = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonHome = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();

        jPanelEscolhaPac.setSize(new java.awt.Dimension(159, 233));

        jLabel2.setText("Escolha o paciente:");

        jButtonSalvarEscolha.setText("Salvar");
        jButtonSalvarEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEscolhaActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF:");

        javax.swing.GroupLayout jPanelEscolhaPacLayout = new javax.swing.GroupLayout(jPanelEscolhaPac.getContentPane());
        jPanelEscolhaPac.getContentPane().setLayout(jPanelEscolhaPacLayout);
        jPanelEscolhaPacLayout.setHorizontalGroup(
            jPanelEscolhaPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscolhaPacLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBoxPacienteEsco, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanelEscolhaPacLayout.createSequentialGroup()
                .addGroup(jPanelEscolhaPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEscolhaPacLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(jPanelEscolhaPacLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonSalvarEscolha))
                    .addGroup(jPanelEscolhaPacLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelEscolhaPacLayout.setVerticalGroup(
            jPanelEscolhaPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolhaPacLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jComboBoxPacienteEsco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonSalvarEscolha)
                .addGap(38, 38, 38))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(492, 165));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Escolha uma das opções do médico:");

        jButtonAcessarPacientes.setText("Acessar Paciente");
        jButtonAcessarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarPacientesActionPerformed(evt);
            }
        });

        jButtonPacientesNoMes.setText("Pacientes no mês");
        jButtonPacientesNoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacientesNoMesActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButtonHome.setText("H");
        jButtonHome.setFocusable(false);
        jButtonHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonHome);

        jButtonAnterior.setText("A");
        jButtonAnterior.setFocusable(false);
        jButtonAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAnterior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAcessarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jButtonPacientesNoMes)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAcessarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPacientesNoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarPacientesActionPerformed
        //String cpf = JOptionPane.showInputDialog(null, "Escreva o cpf do paciente:", "Acesso ao Paciente", JOptionPane.INFORMATION_MESSAGE);
        //Paciente paciente = buscaPacienteConsulta(medico.getConsulta(), cpf);
        
        jPanelEscolhaPac.setVisible(true);
        
        List<String> pacientesMed = medico.imprimirNomePacientes();
        for(String x: pacientesMed){
            jComboBoxPacienteEsco.addItem(x);
        }
    }//GEN-LAST:event_jButtonAcessarPacientesActionPerformed

    private void jButtonPacientesNoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacientesNoMesActionPerformed
        String  data = JOptionPane.showInputDialog(null, "Digite o mês que deseja consultar: (0x)", "Pacientes no mês", JOptionPane.INFORMATION_MESSAGE);
        String pacientes = medico.pacienteMes(data);
        JOptionPane.showMessageDialog(null, pacientes, "Pacientes atendidos no mês", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonPacientesNoMesActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        dispose();
        MenuEntrar main = new MenuEntrar(clinica);
        main.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        dispose();
        MenuLogin log = new MenuLogin(clinica);
        log.setVisible(true);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSalvarEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEscolhaActionPerformed
        String cpf = (String) jComboBoxPacienteEsco.getSelectedItem();
        
        
        Paciente paciente = buscaPacienteConsulta(medico.getConsulta(), cpf);
        
        MenuMedPac menuPac = new MenuMedPac(clinica, medico, paciente);
        menuPac.setVisible(true);
        jPanelEscolhaPac.dispose();
        dispose();
    }//GEN-LAST:event_jButtonSalvarEscolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessarPacientes;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonPacientesNoMes;
    private javax.swing.JButton jButtonSalvarEscolha;
    private javax.swing.JComboBox<String> jComboBoxPacienteEsco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFrame jPanelEscolhaPac;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
