/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import atoresPrincipais.Clinica;
import atoresPrincipais.Secretaria;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class MenuEntrar extends javax.swing.JFrame {

    /**
     * Creates new form MenuEntrar
     */
    Clinica clinica = new Clinica("Saude & CIA", new Secretaria("Vanessa"));
    public MenuEntrar() {
        initComponents();
    }
    
    public MenuEntrar(Clinica clinica) {
        this.clinica = clinica;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameCadastroMed = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jButtonCadastraMed = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCRM = new javax.swing.JTextField();
        jComboBoxEspecialidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFrameEmailSms = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextAreaImprimirEmails = new javax.swing.JTextArea();
        jTextAreaImprimirSMS = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMenuLogin = new javax.swing.JButton();
        btnGerenciadorMensagem = new javax.swing.JButton();
        btnExibirMedicos = new javax.swing.JButton();
        btnCadastroMedico = new javax.swing.JButton();

        jFrameCadastroMed.setTitle("Cadastrar Médico");
        jFrameCadastroMed.setSize(new java.awt.Dimension(400, 330));
        jFrameCadastroMed.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cadastrar novo Médico:");
        jFrameCadastroMed.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 19, -1, -1));

        jButtonCadastraMed.setText("Cadastrar");
        jButtonCadastraMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraMedActionPerformed(evt);
            }
        });
        jFrameCadastroMed.getContentPane().add(jButtonCadastraMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 250, 99, 36));
        jFrameCadastroMed.getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 82, 170, -1));
        jFrameCadastroMed.getContentPane().add(jTextFieldCRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 139, 170, -1));

        jComboBoxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ortopedista", "Pneumologista", "Cardiologista", "Neurologista", "Oftalmologista" }));
        jFrameCadastroMed.getContentPane().add(jComboBoxEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 193, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");
        jFrameCadastroMed.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 84, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Crm:");
        jFrameCadastroMed.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 141, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Especialidade:");
        jFrameCadastroMed.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 195, -1, -1));

        jFrameEmailSms.setSize(new java.awt.Dimension(943, 411));
        jFrameEmailSms.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jFrameEmailSmsComponentShown(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Emails");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("SMS");

        jTextAreaImprimirEmails.setColumns(20);
        jTextAreaImprimirEmails.setRows(5);
        jTextAreaImprimirEmails.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextAreaImprimirSMS.setColumns(20);
        jTextAreaImprimirSMS.setRows(5);
        jTextAreaImprimirSMS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameEmailSmsLayout = new javax.swing.GroupLayout(jFrameEmailSms.getContentPane());
        jFrameEmailSms.getContentPane().setLayout(jFrameEmailSmsLayout);
        jFrameEmailSmsLayout.setHorizontalGroup(
            jFrameEmailSmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEmailSmsLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(220, 220, 220))
            .addGroup(jFrameEmailSmsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextAreaImprimirEmails, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jTextAreaImprimirSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameEmailSmsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jFrameEmailSmsLayout.setVerticalGroup(
            jFrameEmailSmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEmailSmsLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jFrameEmailSmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jFrameEmailSmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAreaImprimirSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAreaImprimirEmails, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Saude & CIA true.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Escolha uma opção:");

        btnMenuLogin.setText("Entrar");
        btnMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLoginActionPerformed(evt);
            }
        });

        btnGerenciadorMensagem.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnGerenciadorMensagem.setText("Enviar Mensagens");
        btnGerenciadorMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciadorMensagemActionPerformed(evt);
            }
        });

        btnExibirMedicos.setText("Mostrar Médicos");
        btnExibirMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMedicosActionPerformed(evt);
            }
        });

        btnCadastroMedico.setText("Cadastrar Médico");
        btnCadastroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGerenciadorMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExibirMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerenciadorMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExibirMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLoginActionPerformed
        dispose();
        MenuLogin log = new MenuLogin(clinica);
        log.setVisible(true);
    }//GEN-LAST:event_btnMenuLoginActionPerformed

    private void btnExibirMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMedicosActionPerformed

        List<String> meds = clinica.imprimirMedicos();
        String impressao = "";
        for(String i : meds){
            impressao = impressao+i+"\n";
        }
        System.out.println(meds);
        
        JOptionPane.showMessageDialog(null, impressao, "Médicos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExibirMedicosActionPerformed

    private void btnCadastroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroMedicoActionPerformed
        jFrameCadastroMed.setVisible(true);
    }//GEN-LAST:event_btnCadastroMedicoActionPerformed

    private void jButtonCadastraMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraMedActionPerformed
        
        if(jTextFieldCRM.getText().isEmpty() || jTextFieldNome.getText().isEmpty() || !(clinica.verificaCRM(jTextFieldCRM.getText()))){
            JOptionPane.showMessageDialog(null, "Erro no Cadastro", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            String esp = (String) jComboBoxEspecialidade.getSelectedItem();
            clinica.cadastraMedico(jTextFieldCRM.getText(), jTextFieldNome.getText(), esp);
        
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            jTextFieldCRM.setText("");
            jTextFieldNome.setText("");
        }
        
        
       
        
        
    }//GEN-LAST:event_jButtonCadastraMedActionPerformed

    private void btnGerenciadorMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciadorMensagemActionPerformed
        
        jFrameEmailSms.setVisible(true);
        
        
    }//GEN-LAST:event_btnGerenciadorMensagemActionPerformed

    private void jFrameEmailSmsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jFrameEmailSmsComponentShown
        String data = JOptionPane.showInputDialog("Escreva a data atual:");
        List<String> emails;
        List<String> SMS;
        emails = clinica.getGerenciador().enviarEmail(data);
        SMS = clinica.getGerenciador().enviarSMS(data);
        String imprimiEmail = "";
        String imprimiSms = "";
        
        for(String i : emails){
            imprimiEmail = imprimiEmail+i+"\n";
        }
        for(String j : SMS){
            imprimiSms = imprimiSms+j+"\n";
        }
        jTextAreaImprimirEmails.setText(imprimiEmail);
        jTextAreaImprimirSMS.setText(imprimiSms);
        
    }//GEN-LAST:event_jFrameEmailSmsComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Mensagens enviadas com sucesso!");
        jFrameEmailSms.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEntrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroMedico;
    private javax.swing.JButton btnExibirMedicos;
    private javax.swing.JButton btnGerenciadorMensagem;
    private javax.swing.JButton btnMenuLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastraMed;
    private javax.swing.JComboBox<String> jComboBoxEspecialidade;
    private javax.swing.JFrame jFrameCadastroMed;
    private javax.swing.JFrame jFrameEmailSms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextAreaImprimirEmails;
    private javax.swing.JTextArea jTextAreaImprimirSMS;
    private javax.swing.JTextField jTextFieldCRM;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
