/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import atoresPrincipais.Clinica;
import clinicaTipos.TipoConsulta;
import clinicaTipos.TipoConvenio;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class MenuSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form MenuSecretaria
     */
    
    Clinica clinica;
    
    public MenuSecretaria(Clinica clinica){
        initComponents();
        this.clinica = clinica;
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameCadastroPac = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextCpf = new javax.swing.JTextField();
        jTextTelefone = new javax.swing.JTextField();
        jTextDataNasc = new javax.swing.JTextField();
        jTextEndereco = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jRadioBtnPlano = new javax.swing.JRadioButton();
        jRadioBtnConvenio = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrameCadConsulta = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButtonNormal = new javax.swing.JRadioButton();
        jRadioButtonRetorno = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldCpfPac = new javax.swing.JTextField();
        jTextFieldCrmMed = new javax.swing.JTextField();
        jTextFieldHorario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAttPacientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonRemoverPac = new javax.swing.JButton();
        jButtonImprimirPac = new javax.swing.JButton();
        jButtonCadastraPaciente = new javax.swing.JButton();
        jButtonCadConsulta = new javax.swing.JButton();
        jButtonRemoveCons = new javax.swing.JButton();
        jButtonAttConsulta = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonConsDiaSeg = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonHome = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();

        jFrameCadastroPac.setSize(new java.awt.Dimension(430, 461));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Insira as Informações:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel6.setText("Cpf:");

        jLabel7.setText("Telefone:");

        jLabel8.setText("Data de Nascimento:");

        jLabel9.setText("Endereco:");

        jLabel10.setText("Email:");

        jLabel11.setText("Convenio:");

        buttonGroup1.add(jRadioBtnPlano);
        jRadioBtnPlano.setText("PLANO");

        buttonGroup1.add(jRadioBtnConvenio);
        jRadioBtnConvenio.setText("Particular");
        jRadioBtnConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnConvenioActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameCadastroPacLayout = new javax.swing.GroupLayout(jFrameCadastroPac.getContentPane());
        jFrameCadastroPac.getContentPane().setLayout(jFrameCadastroPacLayout);
        jFrameCadastroPacLayout.setHorizontalGroup(
            jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(59, 59, 59)
                                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEndereco)
                                    .addComponent(jTextDataNasc)
                                    .addComponent(jTextEmail)))
                            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jRadioBtnPlano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jRadioBtnConvenio))))
                    .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrameCadastroPacLayout.setVerticalGroup(
            jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadastroPacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jFrameCadastroPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jRadioBtnPlano)
                    .addComponent(jRadioBtnConvenio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jFrameCadConsulta.setSize(new java.awt.Dimension(417, 476));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Insira as Informações:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Horario:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Data");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Cpf do Paciente:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Crm do Medico:");

        buttonGroup1.add(jRadioButtonNormal);
        jRadioButtonNormal.setText("Normal");

        buttonGroup1.add(jRadioButtonRetorno);
        jRadioButtonRetorno.setText("Retorno");

        jLabel17.setText("Tipo de Consulta:");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameCadConsultaLayout = new javax.swing.GroupLayout(jFrameCadConsulta.getContentPane());
        jFrameCadConsulta.getContentPane().setLayout(jFrameCadConsultaLayout);
        jFrameCadConsultaLayout.setHorizontalGroup(
            jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButtonNormal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(jRadioButtonRetorno))))
                    .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameCadConsultaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCrmMed, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                        .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrameCadConsultaLayout.setVerticalGroup(
            jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadConsultaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(42, 42, 42)
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldCrmMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jFrameCadConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNormal)
                    .addComponent(jRadioButtonRetorno))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Opções relacionadas a secretaria:");

        jButtonAttPacientes.setText("Atualizar Paciente (N)");
        jButtonAttPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttPacientesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Consultas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Paciente");

        jButtonRemoverPac.setText("Remover Paciente");
        jButtonRemoverPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPacActionPerformed(evt);
            }
        });

        jButtonImprimirPac.setText("Imprimir Pacientes");
        jButtonImprimirPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirPacActionPerformed(evt);
            }
        });

        jButtonCadastraPaciente.setText("Cadastrar Paciente");
        jButtonCadastraPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraPacienteActionPerformed(evt);
            }
        });

        jButtonCadConsulta.setText("Cadastrar Consulta");
        jButtonCadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadConsultaActionPerformed(evt);
            }
        });

        jButtonRemoveCons.setText("Remover Consulta");
        jButtonRemoveCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveConsActionPerformed(evt);
            }
        });

        jButtonAttConsulta.setText("Atualizar Consulta (N)");
        jButtonAttConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttConsultaActionPerformed(evt);
            }
        });

        jButton8.setText("Imprimir Consultas");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonConsDiaSeg.setText("Gerar Relatorio de Consultas ");
        jButtonConsDiaSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsDiaSegActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButtonHome.setText("H");
        jButtonHome.setFocusable(false);
        jButtonHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonHome);

        jButtonAnterior.setText("A");
        jButtonAnterior.setFocusable(false);
        jButtonAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAnterior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRemoverPac, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastraPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAttPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImprimirPac, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButtonConsDiaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAttConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoveCons, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastraPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverPac, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAttPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImprimirPac, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConsDiaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoveCons, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAttConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAttPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttPacientesActionPerformed
        // A FAZER DEPOIS DE TERMINAR O BD
    }//GEN-LAST:event_jButtonAttPacientesActionPerformed

    private void jButtonRemoverPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPacActionPerformed
        String cpf = JOptionPane.showInputDialog(null, "Escreva o cpf do paciente", "Remover", JOptionPane.INFORMATION_MESSAGE);
   
        if(clinica.testaPaciente(cpf)){
            clinica.getSecretaria().removePaciente(cpf);
            JOptionPane.showMessageDialog(null, "Removido com sucesso", "Removido", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Não encontrado!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonRemoverPacActionPerformed

    private void jButtonImprimirPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirPacActionPerformed
        String Pacs = clinica.imprimirSecretariaPacientes();
        
        JOptionPane.showMessageDialog(null, Pacs, "Pacientes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonImprimirPacActionPerformed

    private void jButtonCadastraPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraPacienteActionPerformed
        jFrameCadastroPac.setVisible(true);
    }//GEN-LAST:event_jButtonCadastraPacienteActionPerformed

    private void jButtonCadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadConsultaActionPerformed
        jFrameCadConsulta.setVisible(true);
    }//GEN-LAST:event_jButtonCadConsultaActionPerformed

    private void jButtonRemoveConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveConsActionPerformed
        String data = JOptionPane.showInputDialog(null, "Escreva a data:", "Inserir Data", HEIGHT);
        String horario = JOptionPane.showInputDialog(null, "Escreva o horario", "Inserir horario", HEIGHT);
        String crm = JOptionPane.showInputDialog(null, "Escreva o crm:", "Inserir CRM", HEIGHT);
        
        clinica.getSecretaria().removeConsulta(crm, data, horario);
        
        JOptionPane.showMessageDialog(null, "Removido com sucesso!", "Remoção", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonRemoveConsActionPerformed

    private void jButtonAttConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAttConsultaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String cons = clinica.imprimirSecretariaConsultas();
        
        JOptionPane.showMessageDialog(null, cons, "Consultas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        dispose();
        MenuEntrar main = new MenuEntrar(clinica);
        main.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        dispose();
        MenuLogin log = new MenuLogin(clinica);
        log.setVisible(true);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonConsDiaSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsDiaSegActionPerformed
        String data = JOptionPane.showInputDialog("Escreva a data de hoje: ");
        
        String consultas = clinica.getSecretaria().gerarRelatorioConsulta(data);
        
        JOptionPane.showMessageDialog(null, consultas, "Consultas do dia Seguinte", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_jButtonConsDiaSegActionPerformed

    private void jRadioBtnConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnConvenioActionPerformed
        
    }//GEN-LAST:event_jRadioBtnConvenioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = jTextNome.getText();
        String cpf = jTextCpf.getText();
        String telefone = jTextTelefone.getText();
        String dataNasc = jTextDataNasc.getText();
        String Endereco = jTextEndereco.getText();
        String Email = jTextEmail.getText();
        
        System.out.println(telefone + " " + Email);
        
        if(telefone.isEmpty()){
            System.out.println("Entrou tel");
            telefone = null;
        }
        if(Email.isEmpty()){
            System.out.println("Entrou Eamail");
            Email = null;
        }
        
        
        if(jRadioBtnPlano.isSelected()){
            clinica.getSecretaria().cadastraPaciente(cpf, nome, dataNasc, Endereco, Email, telefone, TipoConvenio.PLANO);
        }else{
            clinica.getSecretaria().cadastraPaciente(cpf, nome, dataNasc, Endereco, Email, telefone, TipoConvenio.PARTICULAR);
        }
        jTextNome.setText("");
        jTextCpf.setText("");
        jTextTelefone.setText("");
        jTextDataNasc.setText("");
        jTextEndereco.setText("");
        jTextEmail.setText("");
        jFrameCadastroPac.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String data = jTextFieldData.getText();
        String cpf = jTextFieldCpfPac.getText();
        String crm = jTextFieldCrmMed.getText();
        String horario = jTextFieldHorario.getText();
        
        if(jRadioButtonNormal.isSelected()){
            clinica.getSecretaria().cadastraConsulta(data, horario, crm, cpf, TipoConsulta.NORMAL, clinica.getMedicos());
        }else{
            clinica.getSecretaria().cadastraConsulta(data, horario, crm, cpf, TipoConsulta.RETORNO, clinica.getMedicos());
        }
        jTextFieldData.setText("");
        jTextFieldCpfPac.setText("");
        jTextFieldCrmMed.setText("");
        jTextFieldHorario.setText("");
        jFrameCadConsulta.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAttConsulta;
    private javax.swing.JButton jButtonAttPacientes;
    private javax.swing.JButton jButtonCadConsulta;
    private javax.swing.JButton jButtonCadastraPaciente;
    private javax.swing.JButton jButtonConsDiaSeg;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonImprimirPac;
    private javax.swing.JButton jButtonRemoveCons;
    private javax.swing.JButton jButtonRemoverPac;
    private javax.swing.JFrame jFrameCadConsulta;
    private javax.swing.JFrame jFrameCadastroPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioBtnConvenio;
    private javax.swing.JRadioButton jRadioBtnPlano;
    private javax.swing.JRadioButton jRadioButtonNormal;
    private javax.swing.JRadioButton jRadioButtonRetorno;
    private javax.swing.JTextField jTextCpf;
    private javax.swing.JTextField jTextDataNasc;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextFieldCpfPac;
    private javax.swing.JTextField jTextFieldCrmMed;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
